name: Open edX Plugin Integration Tests with Tutor
description: "A Github action to test your plugin in Tutor (Open edX distribution)"
inputs:
  app_name:
    description: "Application name to test. E.g., eox-tenant."
    required: true
  tutor_version:
    description: "The tutor version matrix to use."
    required: true
  shell_file_to_run:
    description: "The path of the shell file to run the integration tests."
    required: true
  openedx_extra_pip_requeriments:
    description: "Optional extra pip requirements to install in Open edX. E.g: 'package1==1.0 package2>=2.0'"
    required: false
    default: ""
  fixtures_file:
    description: "Optional path to the plugin's fixtures file to load."
    required: false
  openedx_imports_test_file_path:
    description: "Path to the file that contains the test function for validating Open edX imports. This should be a Python file within your project."
    required: false
  openedx_imports_test_function_name:
    description: "Name of the function in the specified file that executes the import tests for Open edX."
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.app_name }}

    - name: Set Tutor environment variables
      run: |
        echo "LMS_HOST=local.edly.io" >> "$GITHUB_ENV"
        echo "CMS_HOST=studio.local.edly.io" >> "$GITHUB_ENV"
        echo "TUTOR_ROOT=$(pwd)" >> "$GITHUB_ENV"
        echo "TUTOR_PLUGINS_ROOT=$(pwd)/plugins/" >> "$GITHUB_ENV"
      shell: bash

    - name: Install and prepare Tutor
      run: |
        if [ "$INPUT_TUTOR_VERSION" = "nightly" ]; then
          git clone --branch=nightly --depth=1 https://github.com/overhangio/tutor.git
          pip install -e "./tutor[full]"
          tutor config save
          tutor images build openedx
        else
          pip install "tutor$INPUT_TUTOR_VERSION"
        fi

        tutor config save --set LMS_HOST=$LMS_HOST --set CMS_HOST=$CMS_HOST
        chmod 777 . -R
        tutor local launch -I
      shell: bash
      env:
        INPUT_TUTOR_VERSION: ${{ inputs.tutor_version }}

    - name: Configure Caddyfile and Open edX settings
      run: |
        mkdir -p plugins
        cp $GITHUB_ACTION_PATH/patches.yml plugins/
        tutor plugins enable patches
      shell: bash

    - name: Add mount for plugin
      run: |
        tutor mounts add "lms:$GITHUB_WORKSPACE/${{ inputs.app_name }}:/openedx/${{ inputs.app_name }}"
        tutor mounts add "cms:$GITHUB_WORKSPACE/${{ inputs.app_name }}:/openedx/${{ inputs.app_name }}"
      shell: bash

    - name: Restart Tutor services to apply mounts
      run: |
        tutor local stop
        tutor local start -d
      shell: bash

    - name: Install plugin as an editable package
      if: ${{ inputs.fixtures_file }}
      run: |
        tutor local exec lms pip install -e /openedx/${{ inputs.app_name }}/
      shell: bash

    - name: Install extra requirements
      run: |
        tutor local exec lms pip install ${{ inputs.openedx_extra_pip_requeriments }}
        tutor local exec cms pip install ${{ inputs.openedx_extra_pip_requeriments }}
      shell: bash

    - name: Run migrations
      run: |
        tutor local exec lms python manage.py lms migrate
        tutor local exec cms python manage.py cms migrate
        tutor local restart
      shell: bash

    - name: Import Demo course
      run: |
        tutor local do importdemocourse
      shell: bash

    - name: Set DEMO_COURSE_ID environment variable
      run: |
        #TODO: remove this once we stop supporting Tutor <18.0.0
        if [ "$INPUT_TUTOR_VERSION" = "<18.0.0" ]; then
          echo "DEMO_COURSE_ID=course-v1:edX+DemoX+Demo_Course" >> $GITHUB_ENV
        else
          echo "DEMO_COURSE_ID=course-v1:OpenedX+DemoX+DemoCourse" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Test Open edX imports in plugin
      if: ${{ inputs.openedx_imports_test_file_path && inputs.openedx_imports_test_function_name }}
      run: |
        echo "Running test for Open edX imports"
        tutor local exec --env PYTHONPATH=/openedx/${{ inputs.app_name }} \
                        --env DJANGO_SETTINGS_MODULE=lms.envs.production \
                        lms python -c "
        import os
        import django
        import importlib.util
        django.setup()

        file_path = '/openedx/${{ inputs.app_name }}/${{ inputs.openedx_imports_test_file_path }}'
        function_name = '${{ inputs.openedx_imports_test_function_name }}'

        # Load the module from the file path
        spec = importlib.util.spec_from_file_location('test_module', file_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        func = getattr(module, function_name)
        func()
        "
      shell: bash

    - name: Load inital data for the tests
      if: ${{ inputs.fixtures_file }}
      run: |
        echo "Copying fixtures file to the LMS container"
        tutor local exec lms python manage.py lms loaddata /openedx/${{ inputs.app_name }}/${{ inputs.fixtures_file }}
      shell: bash

    - name: Curl Heartbeat
      run: |
        echo "Curling LMS heartbeat"
        status_code=$(curl -s -o /dev/null -w "%{http_code}" http://$LMS_HOST/heartbeat)
        if [ "$status_code" -ne 200 ]; then
          echo "Error: LMS Heartbeat endpoint returned status code $status_code"
          exit 1  # Exit with non-zero code to fail the workflow
        else
          echo "Heartbeat endpoint returned status code 200"
        fi
      shell: bash

    - name: Run integration tests
      if: ${{ inputs.shell_file_to_run }}
      run: |
        echo "Creating isolated venv to run the tests"
        python -m venv .venv
        source .venv/bin/activate

        cd ${{ inputs.app_name }}
        chmod +x ./${{ inputs.shell_file_to_run }}
        ./${{ inputs.shell_file_to_run }}
      shell: bash
