name: Integration Test in Tutor
description: 'A Github action to test your plugin in Tutor (Open edX distribution)'
inputs:
  app_name:
    description: 'Application name to test. E.g., eox-tenant.'
    required: true
  tutor_version:
    description: 'The tutor version matrix to use.'
    required: true
  shell_file_to_run:
    description: 'The path of the shell file to run the integration tests.'
    required: false

runs:
  using: 'composite'
  steps:
  - name: Prepare Tutor and Launch
    run: |
      pip install "tutor$INPUT_TUTOR_VERSION"
      TUTOR_ROOT="$(pwd)" tutor --version
      TUTOR_ROOT="$(pwd)" tutor config save
      TUTOR_ROOT="$(pwd)" tutor mounts add lms,cms,lms-worker,cms-worker:$(pwd)/$INPUT_APP:/openedx/$INPUT_APP
      chmod 777 . -R
      TUTOR_ROOT="$(pwd)" tutor local launch -I
    shell: bash
    env:
      INPUT_APP: ${{ inputs.app_name }}
      INPUT_TUTOR_VERSION: ${{ inputs.tutor_version }}

  - name: Check LMS heartbeat endpoint
    run: |
      curl -f http://www.myopenedx.com:8000/heartbeat
    shell: bash

  - name: Run integration tests in lms
    if: ${{ inputs.shell_file_to_run }}
    run: |
      TUTOR_ROOT="$(pwd)" tutor local run lms bash $INPUT_SHELL_FILE
    shell: bash
    env:
      INPUT_SHELL_FILE: /openedx/${{ inputs.app_name }}/${{ inputs.shell_file_to_run }}
