name: Open edX Plugin Integration Tests with Tutor
description: 'A Github action to test your Open edX plugin in Tutor'
inputs:
  app_name:
    description: 'Open edX plugin or application name to test. E.g., eox-tenant.'
    required: true
  tutor_version:
    description: 'The tutor version matrix to use.'
    required: true
  python_version:
    description: 'Python version to use.'
    required: false
    default: '3.11'
  tutor_plugins:
    description: "The list of Tutor indexed plugins to install. E.g: 'plugin1 plugin2'"
    required: false
  inline_tutor_plugins_folder:
    description: "Optional path to the folder containing the inline Tutor plugins to install. E.g: 'plugins'"
    required: false
  tutor_extra_commands_path:
    description: 'The path of the shell file to run the extra Tutor commands.'
    required: false
  shell_file_to_run:
    description: 'The path of the shell file to run the integration tests.'
    required: true
    default: 'scripts/execute_integration_tests.sh'
  openedx_extra_pip_requirements:
    description: "Optional extra pip requirements to install in Open edX. E.g: 'package1==1.0 package2>=2.0'"
    required: false
  fixtures_file:
    description: "Optional path to the plugin's fixtures file to load."
    required: false
  openedx_imports_test_file_path:
    description: 'Path to the file that contains the test function for validating Open edX imports. This should be a Python file within your project.'
    required: false
  ssh_private_key:
    description: 'Service user SSH key for repository checkout'
    required: false
  openedx_private_requirements:
    description: "Optional list of SSH Git repos to install inside Open edX. E.g: 'git@github.com:org/repo1.git@main git@github.com:org/repo2.git@v1.0.0'"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.app_name }}

    - name: Adjust permissions to execute Tutor commands
      run: |
        chmod 777 . -R
      shell: bash

    - name: Set Up plugins directory
      run: |
        mkdir -p plugins
      shell: bash

    - name: Set Tutor environment variables
      run: |
        cat <<EOF >> "$GITHUB_ENV"
        LMS_HOST=local.edly.io
        CMS_HOST=studio.local.edly.io
        TUTOR_ROOT=$(pwd)
        TUTOR_PLUGINS_ROOT=$(pwd)/plugins/
        EOF
      shell: bash

    - name: Create virtualenvs
      run: |
        echo "Creating isolated venv for Tutor"
        python -m venv .tutor_venv
        echo "Creating isolated venv to run the integration tests"
        python -m venv .tests_venv
      shell: bash

    - name: Install and prepare Tutor
      env:
        INPUT_TUTOR_VERSION: ${{ inputs.tutor_version }}
      run: |
        source .tutor_venv/bin/activate

        if [ "$INPUT_TUTOR_VERSION" = "main" ]; then
          git clone --branch=main --depth=1 https://github.com/overhangio/tutor.git
          pip install -e ./tutor
        else
          pip install "tutor$INPUT_TUTOR_VERSION"
        fi

        tutor config save --set LMS_HOST=$LMS_HOST --set CMS_HOST=$CMS_HOST
      shell: bash

    - name: Install and enable Tutor index plugins
      if: ${{ inputs.tutor_plugins }}
      run: |
        source .tutor_venv/bin/activate

        tutor plugins update
        tutor plugins install ${{ inputs.tutor_plugins }}
        tutor plugins enable ${{ inputs.tutor_plugins }}
      shell: bash

    - name: Copy patches.yml to plugins directory
      run: |
        source .tutor_venv/bin/activate

        cp $GITHUB_ACTION_PATH/patches.yml plugins/
      shell: bash

    - name: Launch Tutor
      run: |
        source .tutor_venv/bin/activate

        tutor local dc down
        rm -rf $(tutor config printroot)/data
        tutor local start -d
        tutor local do init
        tutor local restart
      shell: bash

    - name: Setup SSH agent for private repositories cloning
      if: ${{ inputs.ssh_private_key }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Add GitHub to known hosts
      run: |
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      shell: bash

    - name: Clone Open edX private pip requirements
      if: ${{ inputs.openedx_private_requirements }}
      run: |
        mkdir -m 777 -p private_requirements
        cd private_requirements

        for entry in ${{ inputs.openedx_private_requirements }}; do
          repo_url="${entry%@*}"
          branch="${entry##*@}"

          echo "Repo URL: $repo_url"
          echo "Branch/Tag: $branch"

          if [ "$repo_url" = "$entry" ]; then
            git clone "$repo_url"
          else
            git clone --branch "$branch" "$repo_url"
          fi
        done

        chmod -R a+rwX .
      shell: bash

    - name: Add mount for private pip requirements
      if: ${{ inputs.openedx_private_requirements }}
      run: |
        source .tutor_venv/bin/activate

        tutor mounts add "lms:$GITHUB_WORKSPACE/private_requirements:/openedx/private_requirements"
        tutor mounts add "cms:$GITHUB_WORKSPACE/private_requirements:/openedx/private_requirements"
      shell: bash

    - name: Add mount for Open edX plugin
      run: |
        source .tutor_venv/bin/activate

        tutor mounts add "lms:$GITHUB_WORKSPACE/${{ inputs.app_name }}:/openedx/${{ inputs.app_name }}"
        tutor mounts add "cms:$GITHUB_WORKSPACE/${{ inputs.app_name }}:/openedx/${{ inputs.app_name }}"
      shell: bash

    - name: Recreate containers to apply mounts
      run: |
        source .tutor_venv/bin/activate

        tutor local start -d lms cms
      shell: bash

    - name: Pip install private requirements inside LMS and CMS
      if: ${{ inputs.openedx_private_requirements }}
      run: |
        source .tutor_venv/bin/activate

        tutor local exec lms bash -c '
          for d in /openedx/private_requirements/*; do
            echo "Installing $d..."
            pip install "$d"
          done
        '
        tutor local exec cms bash -c '
          for d in /openedx/private_requirements/*; do
            echo "Installing $d..."
            pip install "$d"
          done
        '
      shell: bash

    - name: Install Open edX plugin as an editable package
      run: |
        source .tutor_venv/bin/activate

        tutor local exec lms pip install -e /openedx/${{ inputs.app_name }}/
        tutor local exec cms pip install -e /openedx/${{ inputs.app_name }}/
      shell: bash

    - name: Copy inline Tutor plugins to the plugins directory
      if: ${{ inputs.inline_tutor_plugins_folder }}
      run: |
        source .tutor_venv/bin/activate

        cp -r "${{ inputs.app_name }}/${{ inputs.inline_tutor_plugins_folder }}"/* plugins/
      shell: bash

    - name: Enable inline Tutor plugins
      run: |
        source .tutor_venv/bin/activate

        for plugin_file in plugins/*; do
          plugin_name=$(basename "$plugin_file" | cut -f1 -d '.')
          tutor plugins enable "$plugin_name"
        done
      shell: bash

    - name: Install extra requirements
      if: ${{ inputs.openedx_extra_pip_requirements }}
      run: |
        source .tutor_venv/bin/activate

        tutor local exec lms pip install ${{ inputs.openedx_extra_pip_requirements }}
        tutor local exec cms pip install ${{ inputs.openedx_extra_pip_requirements }}
      shell: bash

    - name: Run migrations and restart services
      run: |
        source .tutor_venv/bin/activate

        tutor local exec lms python manage.py lms migrate
        tutor local exec cms python manage.py cms migrate
        tutor local restart
      shell: bash

    - name: Import Demo course
      run: |
        source .tutor_venv/bin/activate

        tutor local do importdemocourse
      shell: bash

    - name: Test Open edX imports in plugin
      if: ${{ inputs.openedx_imports_test_file_path }}
      run: |
        source .tutor_venv/bin/activate

        tutor local exec lms bash -c "pip install pytest pytest-django"
        tutor local exec lms bash -c "pytest -s --ds=lms.envs.tutor.test /openedx/${{ inputs.app_name }}/${{ inputs.openedx_imports_test_file_path }}"
      shell: bash

    - name: Load initial data for the tests
      if: ${{ inputs.fixtures_file }}
      run: |
        source .tutor_venv/bin/activate

        echo "Copying fixtures file to the LMS container"
        tutor local exec lms python manage.py lms loaddata /openedx/${{ inputs.app_name }}/${{ inputs.fixtures_file }}
      shell: bash

    - name: Curl Heartbeat
      run: |
        echo "Curling LMS heartbeat"
        status_code=$(curl -s -o /dev/null -w "%{http_code}" http://$LMS_HOST/heartbeat)
        if [ "$status_code" -ne 200 ]; then
          echo "Error: LMS Heartbeat endpoint returned status code $status_code"
          exit 1
        else
          echo "Heartbeat endpoint returned status code 200"
        fi
      shell: bash

    - name: Set DEMO_COURSE_ID environment variable
      run: |
        #TODO: remove this once we stop supporting Tutor <18.0.0
        if [ "${{ inputs.tutor_version }}" = "<18.0.0" ]; then
          echo "DEMO_COURSE_ID=course-v1:edX+DemoX+Demo_Course" >> $GITHUB_ENV
        else
          echo "DEMO_COURSE_ID=course-v1:OpenedX+DemoX+DemoCourse" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Run extra Tutor commands
      if: ${{ inputs.tutor_extra_commands_path }}
      run: |
        source .tutor_venv/bin/activate

        cd ${{ inputs.app_name }}
        chmod +x ./${{ inputs.tutor_extra_commands_path }}
        ./${{ inputs.tutor_extra_commands_path }}
      shell: bash

    - name: Run integration tests
      env:
        DEMO_COURSE_ID: ${{ env.DEMO_COURSE_ID }}
      run: |
        source .tests_venv/bin/activate

        cd ${{ inputs.app_name }}
        chmod +x ./${{ inputs.shell_file_to_run }}
        ./${{ inputs.shell_file_to_run }}
      shell: bash
