name: Integration Test in Tutor
description: "A Github action to test your plugin in Tutor (Open edX distribution)"
inputs:
  app_name:
    description: "Application name to test. E.g., eox-tenant."
    required: true
  tutor_version:
    description: "The tutor version matrix to use."
    required: true
  shell_file_to_run:
    description: "The path of the shell file to run the integration tests."
    required: false
  tests_path:
    description: "The path of the integration tests."
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Print Current Directory and Files
      run: |
        echo "Current directory and files"
        pwd
        ls -la
      shell: bash

    - name: Prepare Tutor
      run: |
        pip install "tutor$INPUT_TUTOR_VERSION"
        which tutor
        tutor --version
        tutor config save # Create the config.yml
        chmod 777 . -R
      shell: bash
      env:
        INPUT_TUTOR_VERSION: ${{ inputs.tutor_version }}

    - name: Launch Tutor
      run: |
        tutor config save --set LMS_HOST=local.edly.io
        tutor config save --set CMS_HOST=studio.local.edly.io
        tutor mounts add lms,cms,lms-worker,cms-worker:$INPUT_APP_NAME:/openedx/$INPUT_APP_NAME
        tutor local launch --non-interactive
        echo "Tutor launched"
      shell: bash
      env:
        INPUT_APP_NAME: ${{ inputs.app_name }}

    - name: Install Plugin
      run: |
        tutor local exec lms pip install -e /openedx/$INPUT_APP_NAME
        tutor local exec cms pip install -e /openedx/$INPUT_APP_NAME
      shell: bash
      env:
        INPUT_APP_NAME: ${{ inputs.app_name }}

    - name: Curl Heartbeat
      run: |
        echo "Curling the heartbeat"
        curl http://local.edly.io/heartbeat
      shell: bash

    # - name: Run Bash Script
    #   if: ${{ inputs.shell_file_to_run }}
    #   run: |
    #     tutor local run lms bash $INPUT_SHELL_FILE
    #   shell: bash
    #   env:
    #     INPUT_SHELL_FILE: /openedx/${{ inputs.app_name }}/${{ inputs.shell_file_to_run }}

    # - name: Run integration tests
    #   run: |
    #     cd $(pwd)/$INPUT_APP_NAME
    #     make install-dev-dependencies
    #     pytest $TEST_PATH
    #   shell: bash
    #   env:
    #     INPUT_APP_NAME: ${{ inputs.app_name }}
    #     TEST_PATH: ${{ inputs.tests_path }}
