name: Tutor Open edX CI

on: [push]

jobs:
  setup-tutor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip curl
          pip3 install tutor

      - name: Configure Tutor plugin
        run: |
          tutor config save
          echo 'Patching Caddyfile...'
          echo "
          {$default_site_port} {
              import proxy 'lms:8000'
          }
          " > $(tutor config printroot)/env/apps/caddy/Caddyfile

          echo 'Patching CMS production settings...'
          echo "ALLOWED_HOSTS = ['*']" > $(tutor config printroot)/env/apps/openedx/settings/cms/production.py

          echo 'Patching LMS production settings...'
          echo "ALLOWED_HOSTS = ['*']" > $(tutor config printroot)/env/apps/openedx/settings/lms/production.py

      - name: Launch Tutor
        run: |
          tutor config save
          tutor local launch -I

      - name: Check Open edX LMS heartbeat
        run: |
          until curl -sSf http://www.myopenedx.com/heartbeat; do
            echo "Waiting for LMS to be ready..."
            sleep 5
          done
          echo "LMS is up and running!"
